import { useMemo } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { WebView } from 'react-native-webview';

import { Colors } from '@/constants/theme';

interface InvoiceHtmlSheetProps {
  /** The invoice rendered from the same template the PDF is made from. */
  html: string | null;
  /** Applied on top of the reader's own pinch zoom. */
  zoom: number;
}

/**
 * The invoice exactly as it prints.
 *
 * Renders the server-rendered template rather than re-implementing the layout
 * natively, so the preview cannot drift from the PDF. Pinch to zoom works
 * because the page is a real document; the zoom buttons set the initial scale.
 */
export function InvoiceHtmlSheet({ html, zoom }: InvoiceHtmlSheetProps) {
  const document = useMemo(() => {
    if (!html) return null;
    // The template is written for A4. Scale it to the phone's width and let
    // the viewport handle pinch zoom from there.
    return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=760, initial-scale=${zoom}, minimum-scale=0.3, maximum-scale=6, user-scalable=yes" />
    <style>
      html, body { margin: 0; padding: 4px; background: #fff; }
    </style>
  </head>
  <body>${html}</body>
</html>`;
  }, [html, zoom]);

  if (!document) {
    return (
      <View style={styles.loading}>
        <ActivityIndicator color={Colors.primary} />
        <Text style={styles.loadingText}>Rendering invoice…</Text>
      </View>
    );
  }

  return (
    <WebView
      originWhitelist={['*']}
      source={{ html: document }}
      style={styles.web}
      // The document is generated by our own API; nothing else may load.
      javaScriptEnabled={false}
      scalesPageToFit
      setBuiltInZoomControls
      setDisplayZoomControls={false}
      scrollEnabled
      showsVerticalScrollIndicator={false}
      androidLayerType="hardware"
    />
  );
}

const styles = StyleSheet.create({
  web: { flex: 1, backgroundColor: '#fff' },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 },
  loadingText: { fontSize: 13, color: Colors.textSecondary },
});
